spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    com.expertsoft.phoneshop: DEBUG

phoneshop:
  plp:
    maxPageSize: 5