spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: c62c8890e77ee4822e60
            clientSecret: 1e227549eb121a157be171f719d95aff31924cf5
          google:
            client-id: 57433330595-u3ns45al52dlcnfnad9d13eov0kb79fl.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    com.expertsoft.phoneshop: DEBUG

phoneshop:
  plp:
    max-page-size: 5
    max-number-of-pages: 3
