spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <github-client-id>
            clientSecret: <github-client-secret>
          google:
            client-id: <google-client-id>
            client-secret: <google-client-secret>



logging:
  level:
    com.expertsoft.phoneshop: DEBUG

phoneshop:
  plp:
    max-page-size: 5
    max-number-of-pages: 3

debug: true